#!/bin/bash

# Project name
project_name="OptimizedAlgorithmLibrary"

# Create project directory
mkdir -p "$project_name/src/algorithms/sorting"
mkdir -p "$project_name/src/algorithms/searching"
mkdir -p "$project_name/src/algorithms/graph"
mkdir -p "$project_name/src/algorithms/optimization"
mkdir -p "$project_name/src/data_structures"
mkdir -p "$project_name/include/algorithms/sorting"
mkdir -p "$project_name/include/algorithms/searching"
mkdir -p "$project_name/include/algorithms/graph"
mkdir -p "$project_name/include/algorithms/optimization"
mkdir -p "$project_name/include/data_structures"
mkdir -p "$project_name/tests/algorithms/sorting"
mkdir -p "$project_name/tests/algorithms/searching"
mkdir -p "$project_name/tests/algorithms/graph"
mkdir -p "$project_name/tests/algorithms/optimization"
mkdir -p "$project_name/tests/data_structures"

# Create sample files
touch "$project_name/src/algorithms/sorting/merge_sort.cpp"
touch "$project_name/src/algorithms/sorting/quick_sort.cpp"
touch "$project_name/src/algorithms/sorting/heap_sort.cpp"
touch "$project_name/src/algorithms/sorting/tim_sort.cpp"
touch "$project_name/src/algorithms/sorting/counting_sort.cpp"
touch "$project_name/src/algorithms/searching/binary_search.cpp"
touch "$project_name/src/algorithms/searching/interpolation_search.cpp"
touch "$project_name/src/algorithms/searching/exponential_search.cpp"
touch "$project_name/src/algorithms/searching/jump_search.cpp"
touch "$project_name/src/algorithms/searching/fibonacci_search.cpp"
touch "$project_name/src/algorithms/graph/bfs.cpp"
touch "$project_name/src/algorithms/graph/dfs.cpp"
touch "$project_name/src/algorithms/graph/dijkstra.cpp"
touch "$project_name/src/algorithms/graph/prim.cpp"
touch "$project_name/src/algorithms/graph/kruskal.cpp"
touch "$project_name/src/algorithms/optimization/knapsack.cpp"
touch "$project_name/src/algorithms/optimization/traveling_salesman.cpp"
touch "$project_name/src/algorithms/optimization/genetic_algorithm.cpp"
touch "$project_name/src/data_structures/linked_list.cpp"
touch "$project_name/src/data_structures/binary_tree.cpp"
touch "$project_name/src/data_structures/hash_table.cpp"
touch "$project_name/include/algorithms/sorting/merge_sort.h"
touch "$project_name/include/algorithms/sorting/quick_sort.h"
touch "$project_name/include/algorithms/sorting/heap_sort.h"
touch "$project_name/include/algorithms/sorting/tim_sort.h"
touch "$project_name/include/algorithms/sorting/counting_sort.h"
touch "$project_name/include/algorithms/searching/binary_search.h"
touch "$project_name/include/algorithms/searching/interpolation_search.h"
touch "$project_name/include/algorithms/searching/exponential_search.h"
touch "$project_name/include/algorithms/searching/jump_search.h"
touch "$project_name/include/algorithms/searching/fibonacci_search.h"
touch "$project_name/include/algorithms/graph/bfs.h"
touch "$project_name/include/algorithms/graph/dfs.h"
touch "$project_name/include/algorithms/graph/dijkstra.h"
touch "$project_name/include/algorithms/graph/prim.h"
touch "$project_name/include/algorithms/graph/kruskal.h"
touch "$project_name/include/algorithms/optimization/knapsack.h"
touch "$project_name/include/algorithms/optimization/traveling_salesman.h"
touch "$project_name/include/algorithms/optimization/genetic_algorithm.h"
touch "$project_name/include/data_structures/linked_list.h"
touch "$project_name/include/data_structures/binary_tree.h"
touch "$project_name/include/data_structures/hash_table.h"
touch "$project_name/tests/algorithms/sorting/test_merge_sort.cpp"
touch "$project_name/tests/algorithms/sorting/test_quick_sort.cpp"
touch "$project_name/tests/algorithms/sorting/test_heap_sort.cpp"
touch "$project_name/tests/algorithms/sorting/test_tim_sort.cpp"
touch "$project_name/tests/algorithms/sorting/test_counting_sort.cpp"
touch "$project_name/tests/algorithms/searching/test_binary_search.cpp"
touch "$project_name/tests/algorithms/searching/test_interpolation_search.cpp"
touch "$project_name/tests/algorithms/searching/test_exponential_search.cpp"
touch "$project_name/tests/algorithms/searching/test_jump_search.cpp"
touch "$project_name/tests/algorithms/searching/test_fibonacci_search.cpp"
touch "$project_name/tests/algorithms/graph/test_bfs.cpp"
touch "$project_name/tests/algorithms/graph/test_dfs.cpp"
touch "$project_name/tests/algorithms/graph/test_dijkstra.cpp"
touch "$project_name/tests/algorithms/graph/test_prim.cpp"
touch "$project_name/tests/algorithms/graph/test_kruskal.cpp"
touch "$project_name/tests/algorithms/optimization/test_knapsack.cpp"
touch "$project_name/tests/algorithms/optimization/test_traveling_salesman.cpp"
touch "$project_name/tests/algorithms/optimization/test_genetic_algorithm.cpp"
touch "$project_name/tests/data_structures/test_linked_list.cpp"
touch "$project_name/tests/data_structures/test_binary_tree.cpp"
touch "$project_name/tests/data_structures/test_hash_table.cpp"
touch "$project_name/CMakeLists.txt"
touch "$project_name/README.md"
touch "$project_name/LICENSE"

# Print completion message
echo "Project structure for $project_name has been created!"
